name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 10 * * *"
  workflow_dispatch:
jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "1376896787@qq.com"
          git config --local user.name "beiklive"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "交公粮"
          git push
